### ISSUE TITLE
FxA notifications Banner

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3554] opened 2019-04-25 14:20 UTC
Notifications banners for FxA. 

See invision wireframes for interaction (do not reference for final designs). 

[Zeplin link](https://zpl.io/amdMYpA)

cc @akatsoulas @kkellydesign @mcranston18

**Comment by kkellydesign** [comment] 2019-04-30 20:18
update: designs for this are done and will be in our next PR: 

<img width="1034" alt="Screen Shot 2019-04-30 at 4 17 34 PM" src="https://user-images.githubusercontent.com/202590/56990603-88a59c80-6b63-11e9-8073-564c0bde5b0b.png">

**Comment by rleitan** [comment] 2019-05-10 10:20
The second banner is displayed on "Edit my profile" but not on "View my profile".
The banner disappears if I go to View my profile then I come bank to Edit my profile, without clicking the "x" button.  Also the banner is not displayed if I re-login. Is this expected?

**Comment by akatsoulas** [comment] 2019-05-13 08:14
@rleitan this is the expected behavior. We are displaying the message once after the account linking. The first page that a user sees after the linking in the edit_profile page and that's the reason the message is displayed only there. Regarding the `x` button is only there for the user to dismiss the banner in the edit profile page. If the page changes the message should not be displayed.

**Closed** 2019-07-03 13:56 UTC
