### ISSUE TITLE
"Delete my account" button is not working

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3877] opened 2019-09-02 08:48 UTC
[Environment]:
Windows 10, Mac 10.14 - Firefox release, Chrome

[STR]:
1.Open https://support.allizom.org/en-US/users/edit
2.Click "Close account and delete all profile information"
3.Enter your username and click "Delete my account" button

[Expected result]:
The account should be deleted

[Actual result]:
Nothing happens

[Note]:
No errors in the Console

**Comment by akatsoulas** [comment] 2019-09-02 08:51
Closing as duplicate of #3841

**Comment by akatsoulas** [comment] 2019-09-02 13:04
Reopening as this is a regression of #3841

**Comment by viorelaioia** [comment] 2019-09-05 08:27
The issue here seems to be the that in step #3 display name was entered, instead of username. When the correct username is not entered, the "Delete my account" button has no effect. 
So the account deletion flow works as expected.

**Closed by viorelaioia** 2019-09-05 08:27 UTC
Labels: Bug

**Comment by michrogit** [comment] 2019-09-05 09:47
Hello, sorry for bothering you, but are you sure? 
Tried now. The "Delete My Account" button doesn't works. I entered several times the correct username but nothing. 
The account I want to delete is this https://support.mozilla.org/it/user/mich.mozilla (I used the Log in / Sign up with Firefox Accounts)
I wrote about this issue in this SUMO community discussions post:
https://support.mozilla.org/it/forums/contributors/713627?last=76549#post-76540

Thanks in advance

**Comment by viorelaioia** [comment] 2019-09-05 11:33
hey @michrogit ! I verified this bug in the staging version, after a [fix](https://github.com/mozilla/kitsune/issues/3841) for closing account issues was added. 
We will do a release in production later today (in ~3h), that includes that fix. Can you please check if you are able to delete your sumo account afterwards?
Thanks!

**Comment by michrogit** [comment] 2019-09-05 11:55
Ciao @viorelaioia :-)
Thank you so much for your fast and kind reply. I'll check later and I let you know ;-)

**Comment by michrogit** [comment] 2019-09-05 16:09
Hooray! I tried now and after few attempts to click on the "Delete My Account" button, it worked!!! 
I clicked 5/6 times and nothing happened but in the end, after yet another click, the account has been deleted displaying this message on the Sumo page:

> Your account was successfully closed!
> We're sorry to see you go.

Now I can use my Firefox Account to log in to my "historical" Sumo account (https://support.mozilla.org/it/user/michro) and to Mozilla Support
Thank you so much for the fix!!!
