### ISSUE TITLE
[staging] User is redirected to homepage after login, instead of initial page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3569] opened 2019-05-02 10:58 UTC
**STR:**

1. Navigate to https://support.allizom.org/en-US/
2. Click "Get community support" button => User is sent to page with url https://support.allizom.org/en-US/questions/new
3. Click "Sign In" button from the header
4. Enter valid credentials, then click "Log In"

**Expected:**
User is redirected to the page from where "Sign In" button was clicked: https://support.allizom.org/en-US/questions/new

**Actual:**
User is redirected to homepage: https://support.allizom.org/en-US/?fpa=1

**Comment by akatsoulas** [comment] 2019-05-03 11:25
This looks like a regression from the Django upgrade. It's not reproducible in prod. cc @SmileyChris @metadave

**Comment by akatsoulas** [comment] 2020-01-06 16:13
closing as duplicate

**Closed by akatsoulas** 2020-01-06 16:13 UTC
