### ISSUE TITLE
Logging in from a certain page redirects the user to Homepage

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3847] opened 2019-07-30 11:58 UTC
**STR:**
1. Navigate to SUMO Firefox product [page](https://support.mozilla.org/en-US/products/firefox)
2. Click "Ask The Community" section on the bottom of the page
3. Click "Get Help" button => User is redirected to login page
4. Click "Continue with firefox accounts" button
5. Enter fxa credentials and login

**Expected results:**
User is redirected to ask a question page

**Actual results:**
User is redirected to Homepage

**Comment by akatsoulas** [comment] 2019-12-16 15:12
This will be fixed in this PR https://github.com/mozilla/kitsune/pull/4087
I am closing this issue as duplicate of #4058

**Closed by akatsoulas** 2019-12-16 15:12 UTC
Labels: Bug
