### ISSUE TITLE
Return error message when username is wrong in account deletion window 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3880] opened 2019-09-05 08:34 UTC
Currently, when deleting a sumo account, users are asked to enter the username, then click "Delete my Account" button. If the username entered is wrong, the button is not functional. 
We should return an error message informing the user that the username is not correct.

**Comment by akatsoulas** [comment] 2019-12-27 11:43
This is duplicate of https://github.com/mozilla/sumo-project/issues/87

**Closed by akatsoulas** 2019-12-27 11:43 UTC
Labels: Feature
