### ISSUE TITLE
Recent searches list is not correctly displayed

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3726] opened 2019-06-07 14:44 UTC
[Environment]:
Mac OS, Ubuntu 16.04, Windows 10 - Firefox
[Precondition]:
Have some recent searches

[STR]:
1.Open https://support.mozilla.org/zh-CN/kb/insecure-password-warning-firefox
2.Click the search field
3.Press Tab key twice

[Expected result]:
The recent searches list should be displayed below the search field

[Actual result]:
There is extra space  between the search field and recent searches list

<img width="1147" alt="Screenshot 2019-06-07 at 17 09 45" src="https://user-images.githubusercontent.com/41474886/59112470-c01a1c80-894b-11e9-9846-303c2edacd0e.png">

**Comment by kkellydesign** [comment] 2019-06-12 15:46
I'm able to reproduce this issue on Firefox for mac. It's happening when the autocomplete suggestions are open when the layout of the page changes. This is a browser default feature, which browsers don't give access to edit via CSS. Since this seems to be causing other problems, I just disabled the default feature by adding `autocomplete=off` to the search input tags sitewide. The fix is included in https://github.com/mozilla/kitsune/pull/3733.

**Closed** 2020-01-06 15:31 UTC
Labels: Bug
